### ISSUE TITLE
linrongbin16 / lin.nvim首页的超链接坏了

### ISSUE THREAD

**Issue by nirvana6** [linrongbin16/lin.nvim#117]
[linrongbin16 / lin.nvim](https://github.com/linrongbin16/lin.nvim)页面的超链接坏了，如下图所示：

<img width="533" alt="image" src="https://github.com/linrongbin16/lin.nvim/assets/2957421/24ff8dea-33b4-4821-a350-7fd11a1f063c">

**Comment by linrongbin16** [comment]
Thanks, fixed in #118
