### ISSUE TITLE
自己安装别人的lua插件没能成功启动

### ISSUE THREAD

**Issue by nirvana6** [linrongbin16/lin.nvim#138]
## 背景

我准备安装插件[focus.nvim](https://github.com/nvim-focus/focus.nvim)

按照lin.nvim的教程[Customization](https://linrongbin16.github.io/lin.nvim.dev/#/user-guide/customization?id=customization)，我的配置如下：

1. 配置用户插件列表：
<img width="1077" alt="image" src="https://github.com/linrongbin16/lin.nvim/assets/2957421/44c4cdbd-1aff-4ac1-abf7-2f186dae8574">

2. 对插件[focus.nvim](https://github.com/nvim-focus/focus.nvim)单独配置：
![image](https://github.com/linrongbin16/lin.nvim/assets/2957421/f9400f5a-5c54-482f-8198-6d7602292d50)

备注：上述配置文件的内容是在终端中预览的，用的是[ranger](https://github.com/ranger/ranger)

## 出现的问题

当我重开nvim，试用[focus.nvim](https://github.com/nvim-focus/focus.nvim)的命令 `:FocusEnable`时被提示无效命令。甚至`:Focus*`都不出现任何该插件的命令（[focus.nvim](https://github.com/nvim-focus/focus.nvim)已经用lazy正常下载和安装，我怀疑没有加载这个[focus.nvim](https://github.com/nvim-focus/focus.nvim)）

~~希望楼主帮我看看我哪里出错了？是不是我的用户插件的配置路径错了？~~

问题已经自查出来了，原来是我没有在`user_plugins.lua`中配置用户插件时，定义config的位置。在`user_plugins.lua`改成如下的配置，能成功加载`focus.nvim`了：
<img width="568" alt="image" src="https://github.com/linrongbin16/lin.nvim/assets/2957421/e07c0241-dac1-428d-9a7f-f90e52e56f62">

希望管理员考虑我下面的**建议**。多谢你的`lin.nvim`，能帮人省很多事情。

## 建议

建议管理员增加一个功能选项，可以在用户配置了插件名单之后，可以为该插件自动生成用户自定义的文件夹路径。这样或许可以减少用户插件路径的错误。

我看了管理员`lin.nvim`的代码，似乎该插件对`org/plugin.lua`这类的名字自动替换成了`org/plugin-lua`。如果没有仔细阅读代码的人，可能不容易配置好争取的用户插件配置文件的路径。

**Comment by linrongbin16** [comment]
lua的文件模块里，`.`是和`/`一样作为路径分隔符的语法，所以lua文件里所有`.`都被默认替换为了`-`

**Comment by nirvana6** [comment]
> 这个提议不错！我回头弄一下，这几天端午节休息了。

老哥休息好了没？这个功能急用~ 
- [mini.align: Align text interactively](https://github.com/echasnovski/mini.align)
- [NeoAI](https://github.com/Bryley/neoai.nvim)

**Comment by linrongbin16** [comment]
这个目录应该是lin.nvim处理的，应该能删除的呀...

**Comment by nirvana6** [comment]
> 这个目录应该是lin.nvim处理的，应该能删除的呀...
> 
> 还是说你指的删除，是从git repo删除？

它好像得手动删除~

**Comment by linrongbin16** [comment]
对，它只是一个普通的lua文件，其实你放着也没事
