### ISSUE TITLE
捐赠的微信和支付宝都坏了

### ISSUE THREAD

**Issue by nirvana6** [linrongbin16/lin.nvim#194]
如下图:

<img width="579" alt="image" src="https://github.com/linrongbin16/lin.nvim/assets/2957421/c188936b-a292-4215-b2cc-490bfe696a33">

看哥们儿最近忙着重构代码. 一想到很快我们就有更方便的软件用了, 忍不住想捐赠. 但是国内常用的微信和支付宝的二维码似乎都404了.

**Comment by linrongbin16** [comment]
fixed in #195

**Comment by linrongbin16** [comment]
感谢，应该再有一两天就能release了
