### ISSUE TITLE
Feature/Plugin Wishlist

### ISSUE THREAD

**Issue by linrongbin16** [linrongbin16/lin.nvim#200]
Hi, feel free to add the feature you want or your favorite plugin to this wish list!

**Comment by nirvana6** [comment]
I suggest two plugin of the same function: 
1. [vim-auto-save](https://github.com/907th/vim-auto-save)
2. [auto-save.nvim](https://github.com/Pocco81/auto-save.nvim)

I use the first one, since I have little lua experience.

**Comment by nirvana6** [comment]
[cmp-dictionary](https://github.com/uga-rosa/cmp-dictionary)
> A dictionary completion source for [nvim-cmp](https:github.com/hrsh7th/nvim-cmp). This plugin provides one of the easiest way to add desired completion candidates to nvim-cmp

**Comment by linrongbin16** [comment]
@nirvana6 , [auto-save.nvim](https://github.com/Pocco81/auto-save.nvim) seems has newer feature and still maintained, added in #217 .

**Comment by nirvana6** [comment]
> @nirvana6 , [auto-save.nvim](https://github.com/Pocco81/auto-save.nvim) seems has newer feature and still maintained, added in #217 .

thx. 😄
