### ISSUE TITLE
Outdated information of lin.nvim-wiki

### ISSUE THREAD

**Issue by nirvana6** [linrongbin16/lin.nvim#203]
In the wiki [Customization](https://github.com/linrongbin16/lin.nvim/wiki/Customization), the information about lsp is outdated, as following shown: 
<img width="744" alt="image" src="https://github.com/linrongbin16/lin.nvim/assets/2957421/4290b5cd-1c21-4048-8017-611420636873">

**Comment by linrongbin16** [comment]
working in progress

**Comment by linrongbin16** [comment]
done writing customization wiki.
