### ISSUE TITLE
error when open nvim (ubuntu)

### ISSUE THREAD

**Issue by li1345200** [linrongbin16/lin.nvim#204]
Error detected while processing /home/khadas/.config/nvim/init.vim:
line   13:
E5105: Error while calling lua chunk: .../khadas/.config/nvim/lua/builtin/utils/
constants.lua:8: attempt to index field 'fn' (a nil value)
line   16:
E5105: Error while calling lua chunk: /home/khadas/.config/nvim/lua/builtin/colo
rs.lua:63: attempt to call field 'nvim_create_user_command' (a nil value)
line   17:
E5105: Error while calling lua chunk: /home/khadas/.config/nvim/lua/builtin/othe
rs.lua:3: loop or previous error loading module 'builtin.utils.constants'

somebody can help?

**Comment by linrongbin16** [comment]
can you upload entire .config/nvim folder and I will check

**Comment by li1345200** [comment]
here
[nvim.zip](https://github.com/linrongbin16/lin.nvim/files/12060339/nvim.zip)
thanks

**Comment by linrongbin16** [comment]
possibly fixed by #206, would you please help test it?

**Comment by linrongbin16** [comment]
no response
