### ISSUE TITLE
`lin.nvim` default key mapping <C-K> conflict to vim's default behavior

### ISSUE THREAD

**Issue by nirvana6** [linrongbin16/lin.nvim#205]
In vim or nvim, `<C-K>` is used to input special character by default. For example, the following input sequence `<C-K> --> <Enter> --> <Enter>` generates `^M`.

However, currently `<C-K>` is mapped as `textDocument/signatureHelper` in lin.nvim. I think nvim's defalut `<C-K>` is more important than `textDocument/signatureHelper`.

**Comment by linrongbin16** [comment]
It is recommended by nvim-lspconfig: https://github.com/neovim/nvim-lspconfig#suggested-configuration


do you have a use case for this key?

**Comment by linrongbin16** [comment]
Hi @nirvana6 , with #206 , you can define your own `user_config.lua` for a plugin.

The `<C-K>` is defined in [nvim-lspconfig/config.lua](https://github.com/linrongbin16/lin.nvim/blob/d5833da23e5d694f96daa188c76ec92235d9e22c/lua/configs/neovim/nvim-lspconfig/config.lua#L143).

Now you create your own `nvim-lspconfig/user_config.lua` file and will replace existing `config.lua`.

**Comment by nirvana6** [comment]
@linrongbin16  I edited [nvim-lspconfig/config.lua](https://github.com/linrongbin16/lin.nvim/blob/d5833da23e5d694f96daa188c76ec92235d9e22c/lua/configs/neovim/nvim-lspconfig/config.lua#L143) directly, changing `<C-k>` into `<C-h>`.

**Comment by linrongbin16** [comment]
The plugin `nvim-lspconfig` is loaded at [plugins/init.lua#L24](https://github.com/linrongbin16/lin.nvim/blob/042bc191791be6703cc301c7a892aba8f4f11bbb/lua/plugins/init.lua#L24),

inside the method `lua_config`, it will first detect if there's a `lua/configs/neovim/nvim-lspconfig/user_conifg.lua` file, if there is, then it will load it as nvim-lspconfig's config. If there's no `user_config.lua` file, then it will load the default `lua/configs/neovim/nvim-lspconfig/config.lua`.
