### ISSUE TITLE
`go: command not found`. Maybe the auto-instll script of `lin.nvim` should get some fixing.

### ISSUE THREAD

**Issue by nirvana6** [linrongbin16/lin.nvim#219]
I followed the install command in `wsl` as following: 
```shell
git clone https://github.com/linrongbin16/lin.nvim ~/.config/nvim && cd ~/.config/nvim && ./install.sh
```

however, some warning shows: 

<img width="652" alt="image" src="https://github.com/linrongbin16/lin.nvim/assets/2957421/63147da5-7208-41be-8986-85ebf5b2b4d9">

Even we can fix this problem by install `go` manually, I still prefer to report this phenomenon.

**Comment by nirvana6** [comment]
Maybe this script, which would auto-install golang, will help: 

[golang-tools-install-script](https://github.com/canha/golang-tools-install-script)

**Comment by linrongbin16** [comment]
Can you manually install `go` and retry `./install.sh` installer?

I will test this issue on my ubuntu VM later.

**Comment by linrongbin16** [comment]
thanks for provide a more popular golang installer, I will test and try it.

**Comment by nirvana6** [comment]
> Can you manually install `go` and retry `./install.sh` installer?

I can instll `golang` manually with the refered script. After installing golang, everything works.

**Comment by linrongbin16** [comment]
Fixed in https://github.com/linrongbin16/lin.nvim/commit/def2ea98cb32ca6f61079a028d96f391aa8b42b1
