### ISSUE TITLE
How to manage user's config

### ISSUE THREAD

**Issue by liaoliaopro** [linrongbin16/lin.nvim#22]
Except using lin.nvim as a nice out-of-box nvim config, I guess most users would also have their own configs like to tune some key mappings , add favoriable plugins or tweak some existing plugins's conf.  

Is there a recommend place to put these user configs? e.g. a `myconf.vim` file where user can add or override config items. the myconf.vim can be loaded after all the other lin.nvim standard conf taking effect. This way, user can fork lin.nvim, only need to modify myconf.vim and dont have to touch the other parts.  If want to update to the latest version of lin.nvim, a simple `git pull upstream` will work fine.

**Comment by linrongbin16** [comment]
需要考虑考虑，如果满足所谓的“大部分用户需求”，和个人的定制化需求。

**Comment by liaoliaopro** [comment]
谢谢。现在安装后会自动生成 `settings.vim`用于存放用户设置，但这个文件对用户来说，后面一般也会做版本管理，保存自己的修改。毕竟用vim大都是程序员。而且这个文件install的时候会被重新覆盖？

我自己的例子，我会fork一份自己的配置，然后会修改leader key映射，另外一些快捷键调整，增加自己习惯的一些插件；之前遇到的烦恼是每次pull upstream时，可能会有冲突要去解决。后来的做法是，对lin.vim的加载项做了一点调整，保持lin.vim原来基本的内容不动，把自己的修改限制到一个myconf.vim中，lin.vim启动时加载myconf.vim。这样和上游就各自更新各自的，就再没遇到冲突。再然后就是lin.vim deprecated了

对新的lin.nvim，期望有一个加载用户设置的扩展点；二是能否考虑一下fork+override myconf.vim这种比较典型的场景。

谢谢做这么棒的nvim distribution.

**Comment by linrongbin16** [comment]
out-of-box 和 个性化配置 其实本质上是有冲突的。每个人理念不一样，到底做多少算 out-of-box， 多少算 个性化，也挺难界定的。我目前也是凭着一些个人经验尝试，不知道会做成什么样子。

**Comment by linrongbin16** [comment]
close for not active.
