### ISSUE TITLE
Frozen aflter enable `pyright` for python lsp completion.

### ISSUE THREAD

**Issue by nirvana6** [linrongbin16/lin.nvim#221]
<img width="678" alt="image" src="https://github.com/linrongbin16/lin.nvim/assets/2957421/cda57d84-bbaa-4b23-8b07-9237cd8c57da">

**Comment by nirvana6** [comment]
I enable `pyright` in the file `setup_handlers.lua` as following screenshot: 

<img width="1135" alt="image" src="https://github.com/linrongbin16/lin.nvim/assets/2957421/1fe93ef2-c8e8-4b17-8027-e8c6c54dd557">

**Comment by nirvana6** [comment]
All the configuration about `Python` is: 

<img width="717" alt="image" src="https://github.com/linrongbin16/lin.nvim/assets/2957421/996bb730-3283-4abb-87e5-2f7764bd31d8">

**Comment by linrongbin16** [comment]
> I enable `pyright` in the file `setup_handlers.lua` as following screenshot:
> 
> <img alt="image" width="1135" src="https://user-images.githubusercontent.com/2957421/254519866-1fe93ef2-c8e8-4b17-8027-e8c6c54dd557.png">
> It's very laggy when I editing python code.

Please remove the `["pyright"] = ...` from `neovim/nvim-lspconfig/setup_handlers.lua`.

1. Since `pyright` is installed via `mason.nvim` and it's a lsp server, you should not setup it in `nvim-lspconfig`. You should setup it in `williamboman/mason-lspconfig-nvim/setup_handlers.lua`.
2. If you just need the default lsp setup, not any custom setup, you don't need to modify the `setup_handlers.lua`. You only need to modify the `setup_handlers.lua` when you need custom.

**Comment by linrongbin16** [comment]
@nirvana6  can you remove the entire `neovim/nvim-lspconfig/setup_handlers.lua` file and restart nvim?

**Comment by nirvana6** [comment]
> @nirvana6 can you remove the entire `neovim/nvim-lspconfig/setup_handlers.lua` file and restart nvim?

@linrongbin16 I just give `lin.nvim` a whole new installation, but the laggy adn frozen edit panel within nvim remain the same.

**Comment by nirvana6** [comment]
I switch the python lsp server from `pyright` to `python-lsp-server`. Then the laggy phenomenon disappeared. 

It is strange. Several days ago, `pyright` works normally.

**Comment by linrongbin16** [comment]
有可能跟最近的更新有关，你可以试一下把这一行注释掉 
https://github.com/linrongbin16/lin.nvim/blob/main/lua/plugins/init.lua#L216 吗？

**Comment by nirvana6** [comment]
> 还有，你有删除 `lua/configs/neovim/nvim-lspconfig/setup_handlers.lua` 这个文件吗？

我一开始就直接把`setup_handler.lua`这个文件删掉了.

**Comment by nirvana6** [comment]
> 有可能跟最近的更新有关，你可以试一下把这一行注释掉 https://github.com/linrongbin16/lin.nvim/blob/main/lua/plugins/init.lua#L216 吗？

注释掉这一行之后,  再打开nvim并编辑python代码(使用pyright作为lsp), 好了很多. 也就是说, 只有在进入文件的那一刻会卡一下, 后面的补全窗口弹出速度勉强可以接受了.

**Comment by linrongbin16** [comment]
因为最近一次更新我给 nvim-lspconfig 设置了懒加载，看来这个设置是不对的，我会revert回去。

**Comment by nirvana6** [comment]
> 因为最近一次更新我给 nvim-lspconfig 设置了懒加载，看来这个设置是不对的，我会revert回去。

先别. 因为同样`nvim-lspconfig`配置, 用`python-lsp-server`就没有性能问题.

**Comment by linrongbin16** [comment]
额......也就差6-7毫秒其实，lspconfig这种组件作为基础组件其实加载优先级是应该靠前的

**Comment by linrongbin16** [comment]
其实nvim config目前比较麻烦的点就是难测试，我基本上修改一些内容都是靠自己做一下测试。
如果有办法做单元测试和性能测试，质量就会提高一大截。

**Comment by nirvana6** [comment]
嗯, 我再另外一台电脑上测试, 基本上可以确定今天我遇到问题的原因了, 大概有两方面:
1. `pyright` 升级到1.1.318版本会带来一些延迟;
2. `lin.nvim`最近的修改导致`pyright`带来的延迟, 我不确定改了什么, 但是我本机上最近commit如下红圈所示:

<img width="602" alt="image" src="https://github.com/linrongbin16/lin.nvim/assets/2957421/06b68bac-58e1-4d7e-a87f-1200aed20504">

**Comment by linrongbin16** [comment]
我去，太感谢啦，我看看这个commit

**Comment by linrongbin16** [comment]
还是要再麻烦你试一下，
1. 删除 plugins/init.lua 里 schemastore neodev neoconf 三个插件：https://github.com/linrongbin16/lin.nvim/blob/main/lua/plugins/init.lua#L30-L41
2. 删除 nvim-lspconfig.lua 里相关的setup：

**Comment by nirvana6** [comment]
> 还是要再麻烦你试一下，
> 
> 1. 删除 plugins/init.lua 里 schemastore neodev neoconf 三个插件：https://github.com/linrongbin16/lin.nvim/blob/main/lua/plugins/init.lua#L30-L41
> 2. 删除 nvim-lspconfig.lua 里相关的setup：https://github.com/linrongbin16/lin.nvim/blob/main/lua/configs/neovim/nvim-lspconfig/config.lua#L2-L3
> 
> 然后重启nvim，看看是否有性能提高？

效果不明显. 看来还是`pyright`升级到1.1.318导致的. 我切换会1.1.317版本, 就好很多; 升级到最新的1.1.318, 延迟、卡顿就很明显. 应该不是`lin.nvim`的原因.

**Comment by nirvana6** [comment]
用了20230403010800的最新的`lin.nvim`, 问题缓解了.
