### ISSUE TITLE
Cannot find lazy module after newly installed

### ISSUE THREAD

**Issue by liaoliaopro** [linrongbin16/lin.nvim#23]
same issue as [https://github.com/linrongbin16/lin.nvim/issues/8](https://github.com/linrongbin16/lin.nvim/issues/8)

![image](https://user-images.githubusercontent.com/2876615/221343416-4a5bf9f6-7a33-47e8-ba4e-fab39c9501f9.png)

**Comment by liaoliaopro** [comment]
have tried the following. it doesnot work.

>
Hi,

Step-1: please remove all lazy plugins:

rm -rf ~/.local/share/nvim/lazy

Step-2: pull and re-install:

cd ~/.nvim && git pull origin main && ./install.sh
#
>

actually there is no `lazy` folder afte installation, so the rm has no help.

**Comment by linrongbin16** [comment]
Hi, @liaoliaopro 
please specify your OS, neovim version.

**Comment by linrongbin16** [comment]
please check, if there is `~/.nvim/lazy` folder in your OS?

**Comment by linrongbin16** [comment]
and `~/.nvim/lua/repo/folke/lazy-nvim` folder in your home dir.

**Comment by linrongbin16** [comment]
Hi @liaoliaopro  安装问题怎么样了啊？

**Comment by liaoliaopro** [comment]
1. win10+wsl
2. neovim v.0.8.3
3. (base) ➜  pwd
/home/bidong/.nvim/lazy/lazy.nvim  # empty dir
4. (base) ➜  lazy-nvim git:(main) pwd
/home/bidong/.nvim/lua/repo/folke/lazy-nvim  # has file config.lua

**Comment by liaoliaopro** [comment]
![image](https://user-images.githubusercontent.com/2876615/221777468-72ab7fbb-e6ba-408c-8ae3-1228f44ccfd6.png)

looks like lazy.nvim is a git submodule? need to git pull it by hand?

**Comment by linrongbin16** [comment]
<img width="935" alt="image" src="https://user-images.githubusercontent.com/6496887/221777688-fa6f41d1-bba1-496b-b4d5-d44efa56665d.png">

**Comment by liaoliaopro** [comment]
现在弹出安装界面了。之前ji几次是没有的。会不会是网络不好导致安装过程没完成？

**Comment by linrongbin16** [comment]
所有插件安装都依赖git从github下载，你如果有proxy的话，先在terminal里设置:
```
export http_proxy=http://127.0.0.1:10809
export https_proxy=http://127.0.0.1:10809
```
然后再安装，所有的网络请求都会走到你的proxy里，git就不会断开了

**Comment by linrongbin16** [comment]
@liaoliaopro  国内使用github，一般都要搭梯子的，没梯子基本没法用。

**Comment by liaoliaopro** [comment]
谢谢。有梯子，这两天已知的原因不太稳定。这个问题我先关了。

**Comment by linrongbin16** [comment]
OK
