### ISSUE TITLE
pop-up info window obscures the sidebar

### ISSUE THREAD

**Issue by nirvana6** [linrongbin16/lin.nvim#233]
# Description

The pop-up information window obscures the sidebar of `vista`. It's annoying because the pop-up window hides the text in the sidebar.

# Solution Proposal

Maybe the pop-up information window should adjust its own location:
1. when there is no sidebar, the default pop-up window position is ok.
2. If the sidebar is opened, the pop-up window shold shif into left, as shown bellow:
![image](https://github.com/linrongbin16/lin.nvim/assets/2957421/f2c6a2f6-6a63-40ea-bb99-258e8e48469d)

# Screenshot or Screen Recording

Please upload screenshot or screen recording here if there's any.

**Current Situation**

<img width="680" alt="image" src="https://github.com/linrongbin16/lin.nvim/assets/2957421/5a48d4c5-cb17-41a6-b435-755b3c84e6d1">

**Comment by linrongbin16** [comment]
thanks, I need  investigats how should to do it

**Comment by nirvana6** [comment]
@linrongbin16  could you tell me the name of the plugin, which is for this notice window? 

I want to put it in right-bottom cornor.

**Comment by linrongbin16** [comment]
you can remove `notify.nvim` from noice dependency in: https://github.com/linrongbin16/lin.nvim/blob/main/lua/plugins/users_sample.lua#L53,

and here: https://github.com/linrongbin16/lin.nvim/blob/main/lua/plugins/users_sample.lua#L57-L61

**Comment by linrongbin16** [comment]
noice其实也没那么fancy，你可以试一下在 postinit.vim (https://github.com/linrongbin16/lin.nvim/blob/main/postinit_sample.vim#L1) 文件里加一句

`set cmdheight=1`

然后删除noice，看看是否符合自己的习惯

**Comment by linrongbin16** [comment]
还有一个方法，就是在这里 https://github.com/linrongbin16/lin.nvim/blob/main/lua/configs/folke/noice-nvim/config.lua#L28 配置noice的路由规则，理论上可以过滤掉一些你不想看到的message，但是我自己用noice的时候也有很多message不知道是从哪发出来的，所以...
这种message的机制确实会有点noisy其实

**Comment by nirvana6** [comment]
> you can remove `notify.nvim` from noice dependency in: https://github.com/linrongbin16/lin.nvim/blob/main/lua/plugins/users_sample.lua#L53,
> 
> and here: https://github.com/linrongbin16/lin.nvim/blob/main/lua/plugins/users_sample.lua#L57-L61
> 
> noice will fallback to moni.notify when there's no notify.

我在这两个地方删除了 nvim-notify, 世界一下子清静多了. 

请问这样直接删除了nvim-notify, 我会不会收不到**必要**的提示信息?

**Comment by linrongbin16** [comment]
> > you can remove `notify.nvim` from noice dependency in: https://github.com/linrongbin16/lin.nvim/blob/main/lua/plugins/users_sample.lua#L53,
> > and here: https://github.com/linrongbin16/lin.nvim/blob/main/lua/plugins/users_sample.lua#L57-L61
> > noice will fallback to moni.notify when there's no notify.
> 
> 我在这两个地方删除了 nvim-notify, 世界一下子清静多了.
> 
> 请问这样直接删除了nvim-notify, 我会不会收不到**必要**的提示信息?

不会的，noice是找不到notify，然后fallback到mini.notify (另一个内置的通知插件)，就是所有信息都在右下角显示，仅仅是样式不一样。

**Comment by nirvana6** [comment]
> 不会的，noice是找不到notify，然后fallback到mini.notify (另一个内置的通知插件)，就是所有信息都在右下角显示，仅仅是样式不一样。

Less is more. 还是这样"不作"的工具好~
