### ISSUE TITLE
nvim some module not found

### ISSUE THREAD

**Issue by Jasonvim** [linrongbin16/lin.nvim#256]
# Description

Bug: Cannot rename the item at 'C:\Users\86135\.nvim' because it is in use.

Error detected while processing UIEnter Autocommands for "*"..User Autocommands for "*":
Error executing lua callback: ...135/AppData/Local/nvim/lazy/lualine.nvim/lua/lualine.lua:432: Error executing lua: vim/_init_packages.lua:64: module 'vim.diagnostic' not found:
no field package.preload['vim.diagnostic']
cache_loader: module vim.diagnostic not found
cache_loader_lib: module vim.diagnostic not found
no file '.\vim\diagnostic.lua'
no file 'D:\scoop\apps\neovim\current\bin\lua\vim\diagnostic.lua'
no file 'D:\scoop\apps\neovim\current\bin\lua\vim\diagnostic\init.lua'
no file '.\vim\diagnostic.dll'
no file 'D:\scoop\apps\neovim\current\bin\vim\diagnostic.dll'

# Platform

Win11 nvim0.9.2

**Comment by linrongbin16** [comment]
Hi, @Jasonvim, looks like your nvim is installed in `D://scoop`.


Can you try to config the `fzfx.nvim` plugin here: https://github.com/linrongbin16/lin.nvim/blob/main/lua/configs/linrongbin16/fzfx-nvim/config.lua.

**Comment by Jasonvim** [comment]
ok

**Comment by linrongbin16** [comment]
Hi @Jasonvim , is your issue solved?

**Comment by linrongbin16** [comment]
close for no response
