### ISSUE TITLE
`cp` error because there is no `neoconf_sample.json`

### ISSUE THREAD

**Issue by agstar** [linrongbin16/lin.nvim#352]
# Description

cp: cannot stat '/home/xx/.config/nvim/neoconf_sample.json': No such file or directory)

Error detected while processing /home/rcl/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/rcl/.config/nvim/lua/builtin/options.lua:40: attempt to index field 'keymap' (a nil value)
stack traceback:
        /home/xx/.config/nvim/lua/builtin/options.lua:40: in main chunk
        [C]: in function 'require'
        /home/xx/.config/nvim/init.lua:11: in main chunk

# Platform

- OS : Linux Mint 21.2 (Victoria)

The error occurred here, because there is not `neoconf_sample.json` in the git folder

```
    # neoconf
    local neoconf="$NVIM_HOME/neoconf.json"
    if [ ! -f $neoconf ]; then
        cp $NVIM_HOME/neoconf_sample.json $neoconf
    fi
```

**Comment by linrongbin16** [comment]
Hi @agstar , thanks for reporting! it's fixed in #353 , please pull main branch and try again.

**Comment by agstar** [comment]
Hi @linrongbin16 ，  After updating the code,  `./install.sh` succeeded. But `nvim`

**Comment by agstar** [comment]
Hi @linrongbin16 ， After updating the code, ./install.sh succeeded. But nvim still contains errors
```
E5113: Error while calling lua chunk: /home/xxx/.config/nvim/lua/builtin/options.lua:40: attempt to index field 'keymap' (a nil value)
stack traceback:
        /home/xxx/.config/nvim/lua/builtin/options.lua:40: in main chunk
        [C]: in function 'require'
        /home/xxx/.config/nvim/init.lua:11: in main chunk
Press ENTER or type command to continue
 ```

**Comment by linrongbin16** [comment]
hi @agstar, this config only support 0.9+ nvim
