### ISSUE TITLE
Please add msys2 support

### ISSUE THREAD

**Issue by qwq233** [linrongbin16/lin.nvim#584]
It's quite similar to origin Linux but using different package name and also it's running on windows.
You can [click here](https://www.msys2.org/) to check details.

**Comment by linrongbin16** [comment]
By "add msys2 support", you mean don't install third-party packages via `scoop` ?

**Comment by qwq233** [comment]
msys2 uses "pacman" as its package manager and provides its own version of neovim. and yes i wanna install 3rd packages via pacman.

Btw when I open the .rs file, neovim crashes directly, there is no log (or I simply didn’t find it), but I plan to open another issue to discuss this problem.

**Comment by linrongbin16** [comment]
no idea, but you can take a look at the pacman for archlinux: https://github.com/linrongbin16/lin.nvim/blob/84e13c1eefc70f756953582fe95306feadd18e66/install#L294

and manual install third-party dependencies.

**Comment by linrongbin16** [comment]
hi @qwq233 , I close this issue now if you don't have any other issues.
