### ISSUE TITLE
Neovim crashes when openning .rs file

### ISSUE THREAD

**Issue by qwq233** [linrongbin16/lin.nvim#585]
I don't find any log and no idea what plugin lead this problem (maybe plugins relating to rust?).
I tried running it in clean mode and it doesn't crash anymore.
Also this problem did not occur when I opened other files like .c or .java files.

OS version: Windows 11 24H2

nvim version:
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```
Console output:
```
[1]    5316 segmentation fault  nvim libs/rust/src/lib.rs
```

**Comment by linrongbin16** [comment]
sorry, msys2 is not supported

**Comment by qwq233** [comment]
> sorry, msys2 is not supported

uh i have this issue even if i use Powershell

**Comment by linrongbin16** [comment]
I think you should first check, if the `nvim` is working without any configs.
