### ISSUE TITLE
how to disable the annoying warnning.

### ISSUE THREAD

**Issue by nirvana6** [linrongbin16/lin.nvim#606]
As shown in the following screenshot. How to disable it? 

![Screenshot from 2024-09-24 13-18-11](https://github.com/user-attachments/assets/1102631d-f049-4baa-bff0-9447127889b4)

**Comment by linrongbin16** [comment]
Looks like you're using `noice.nvim` or `notify` plugin?

You will need to configure that plugin to disable the warning message (which is a drawback in my opinion)

**Comment by linrongbin16** [comment]
你会说中文吗？这个warning是 "noice.nvim" 或者 "notify.nvim" 插件带来的效果，你需要自己去配置 这两个 插件来disable 这些warning message。我的config里没有对这两个插件做很合适的配置。

**Comment by nirvana6** [comment]
哦，我以为你倾向于使用英语交流呢。

是这样的：最一开始我同时enable了`noice.nvim`和`notify.nvim`两个插件——当然这不是问题的重点。目前我只使用`noice.nvim`插件。

现在我还在读`noice.nvim`的help。

**Comment by linrongbin16** [comment]
我都可以，只是默认用英语。

noice虽然提供一些过滤功能，但也不是很容易配置，我以前尝试过。
