### ISSUE TITLE
module 'lazy' not found & Cannot find color scheme 'kanagawa' after installation

### ISSUE THREAD

**Issue by ADkun** [linrongbin16/lin.nvim#8]
![image](https://user-images.githubusercontent.com/33215032/215644799-ad34de62-66a2-4f37-b050-9f29437bfd39.png)

**Comment by linrongbin16** [comment]
Hi,

Step-1: please remove all lazy plugins:
```
rm -rf ~/.local/share/nvim/lazy
```

Step-2: run command to first initialize lazy and plugins:
```
nvim -c "Lazy! sync"
```

**Comment by linrongbin16** [comment]
Hi, @ADkun, may I ask what is your font?

**Comment by linrongbin16** [comment]
Hi @ADkun , if you have this issue on windows, the issue could because a cross platform error.
I have tried to use cross-platform path separator (for Windows it's '\\', for *NIX it's '/').
Please try again.

**Comment by linrongbin16** [comment]
close for no long active
