### ISSUE TITLE
请问大佬的lin.nvim什么时候发布第一个release

### ISSUE THREAD

**Issue by nirvana6** [linrongbin16/lin.nvim#86]
如题。

最近用了十年的.vimrc丢失。急需一个完整、流畅的日常编辑器使用。我以前.vimrc的插件比较陈旧了，也想趁此机会把以下功能更新到当前state of the art的插件，至少包括：
- 高效编辑（包括跳转、查找、多关键词高亮）
- 代码补全

另外，管理员能否给出一个`lin.nvim`将要支持的插件的roadmap？多谢。

**Comment by linrongbin16** [comment]
其实目前插件已经稳定了，我后续在master上的改动会更加小心谨慎一点，不做break change。

没有roadmap，除非发现有特别有用的新插件。
