### ISSUE TITLE
<Space> f 无法调用telescope的find_files命令，但是手动输入telescope=>find_files可以

### ISSUE THREAD

**Issue by nirvana6** [linrongbin16/lin.nvim#90]
今天安装并试用`lin.nvim`，发现按照官方教程[Search File](https://linrongbin16.github.io/lin.nvim.dev/#/user-guide/search?id=search-file)的指令`<Space>f`，无法正常执行搜索文件的功能，如下图：

<img width="923" alt="space-f无法使用telescope的find_files - Screenshot 2023-05-01 195652" src="https://user-images.githubusercontent.com/2957421/235449172-5fd0b61a-7b3c-4552-bd34-d14152b3388b.png">

但是我在neovim中手动输入如下命令序列则可以执行Telecope的find_files功能：`:Telescope` ==> `find_files`，如下图：

<img width="963" alt="手动输入指令，使用telescope的find_files - Screenshot 2023-05-01 195652" src="https://user-images.githubusercontent.com/2957421/235449206-fb8aabcc-c175-45a9-b590-e740e4d410d7.png">

PS. 

1. 我的平台是`windows 11, wsl(ubuntu)`，所有关于`lin.nvim`的使用经验就是《[进化 neovim 到 lin.nvim 风味](https://papers.fun/2023/05/01/%E6%8A%8Aneovim%E8%BF%81%E7%A7%BB%E5%88%B0%E7%8E%B0%E4%BB%A3%E5%8C%96%E7%9A%84%E7%89%88%E6%9C%AC%EF%BC%9Alin-nvim/)》.
2. 管理员能不能推荐`基于lua语言的neovim配置方法`的短平快教程（能达到用`lua`配置`neovim`的程度就行）。

**Comment by linrongbin16** [comment]
请问是在 Windows 下直接使用nvim，还是在 wsl（ubuntu虚拟机）内使用的nvim？

**Comment by linrongbin16** [comment]
麻烦先试一下 `:WhichKey` 命令，查看 `<space>f` 是否有key mapping

**Comment by linrongbin16** [comment]
`<space>f` 是在 [nvim-telescope/telescope-nvim/keys.lua](https://github.com/linrongbin16/lin.nvim/blob/main/lua/repo/nvim-telescope/telescope-nvim/keys.lua#L6) 这个文件定义的

**Comment by linrongbin16** [comment]
在wsl里安装lin.nvim的时候，实际是识别为ubuntu来安装的。我现在用的脚本里，其实是会安装rustc/cargo，然后通过cargo安装fd命令的。我回头试一下ubuntu下面的安装脚本是不是有bug

**Comment by linrongbin16** [comment]
也能用fzf命令...我一开始不知道这个

**Comment by nirvana6** [comment]
> 

我看了`apt.sh`的源文件，应该是没有安装`rg`和`fd-find`。但我不会改~

**Comment by nirvana6** [comment]
> 

我看了apt.sh的源文件，应该是没有安装rg和fd-find。但我不会改~

**Comment by nirvana6** [comment]
> 在wsl里安装lin.nvim的时候，实际是识别为ubuntu来安装的。我现在用的脚本里，其实是会安装rustc/cargo，然后通过cargo安装fd/bat/rg等命令的。我回头试一下ubuntu下面的安装脚本是不是有bug

我看了apt.sh的源文件，应该是没有安装rg和fd-find。但我不会改~

**Comment by linrongbin16** [comment]
我找时间会在windows上debug一下

**Comment by nirvana6** [comment]
> 我看了`apt.sh`的源文件，应该是没有安装`rg`和`fd-find`。但我不会改~

问题解决了。最开始`./install.sh`之所以没有安装`rg`和`fd-find`，是因为这两个软件是用`cargo`安装的。然而在运行`./install.sh`过程中，环境变量没有识别到`cargo`的路径。


解决方法是：在`~/.zshrc`文件末尾添加`source ~/.cargo/env`。然后在`~/.nvim`中重新运行`./install.sh`。

请关闭该问题。谢谢帮助。

**Comment by linrongbin16** [comment]
....额，你是说我变现么？

**Comment by linrongbin16** [comment]
你写文章当然也是帮我宣传了，哈哈感谢

**Comment by nirvana6** [comment]
我在自己博文《[lin.nvim 中安装其它插件](https://papers.fun/2023/05/11/lin-nvim%E4%B8%AD%E5%AE%89%E8%A3%85%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/)》中，对`lin.nvim`的文件层级结构做了猜测和解读，您看看是不是这么回事儿？多谢。如下：

1. `~/.nvim/init.vim`：neovim的启动文件，用户不用管。
2. `~/.nvim/cfg`：启动时需要加载的配置文件，用户不用管。
3. `~/.nvim/deps`：不同操作系统的软件包管理工具，用户不用管。
4. `~/.nvim/lazy`：从GitHub上clone下来的插件源代码，用户不用管。
5. `~/.nvim/lua`：在lin.nvim的定义中——
	1. `~/.nvim/lua/cfg`：这是“系统级”配置文件所在位置，用户“**一般**”不用管。
	2. ` ~/.nvim/lua/repo`：该文件夹是插件们各自的配置文件，**用户可以在这里进行自定义配置**。
6. ` ~/.nvim/repo`：这是作者用来安装lin.nvim的vim插件的地方。

**Comment by linrongbin16** [comment]
嗯，基本上是这样子的。

自定义插件：[user_plugins.lua](https://github.com/linrongbin16/lin.nvim/blob/main/lua/cfg/user_plugins_sample.lua)

自定义lsp server：
* [mason-lspconfig/ensure_installed.lua](https://github.com/linrongbin16/lin.nvim/blob/7abe4bc3b4eb250dc9bd21f9aaf37b4d4ca4b7c3/lua/repo/williamboman/mason-lspconfig-nvim/ensure_installed_sample.lua#L1) + [mason-lspconfig/setup_handlers.lua](https://github.com/linrongbin16/lin.nvim/blob/7abe4bc3b4eb250dc9bd21f9aaf37b4d4ca4b7c3/lua/repo/williamboman/mason-lspconfig-nvim/setup_handlers_sample.lua#L1)
* [mason-null-ls/ensure_installed.lua](https://github.com/linrongbin16/lin.nvim/blob/7abe4bc3b4eb250dc9bd21f9aaf37b4d4ca4b7c3/lua/repo/jay-babu/mason-null-ls-nvim/ensure_installed_sample.lua#L1) + [mason-null-ls/setup_handlers.lua](https://github.com/linrongbin16/lin.nvim/blob/7abe4bc3b4eb250dc9bd21f9aaf37b4d4ca4b7c3/lua/repo/jay-babu/mason-null-ls-nvim/setup_handlers_sample.lua#L1)
* [lspconfig/setup_handlers.lua](https://github.com/linrongbin16/lin.nvim/blob/7abe4bc3b4eb250dc9bd21f9aaf37b4d4ca4b7c3/lua/repo/neovim/nvim-lspconfig/setup_handlers_sample.lua)

自定义vim配置：[cfg/user.vim](https://github.com/linrongbin16/lin.nvim/blob/main/cfg/other.vim#L45)

**Comment by linrongbin16** [comment]
solved
